version: "3.0"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=neighbours
      - MYSQL_USER=mymy
      - MYSQL_PASSWORD=passw0rd
    volumes:
      - ./docker/mariadb:/config
      # - ./SQLSchema/NeighboursSchema.sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: unless-stopped