version: "3.0"
services:
  adminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=dracula
    restart: always
    ports:
      - 8080:8080
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=hasseNisse#34
      - MYSQL_DATABASE=AlienColony #optional
      - MYSQL_USER=pontus #optional
      - MYSQL_PASSWORD=nisseHasse#34 #optional
    volumes:
      - ./appdata/mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
